build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [py-scrutinizer-run]

filter:
    excluded_paths:
        - "tests/"
        # Everything in a root level "tests" directory will be excluded
    dependency_paths:
        - "lib/"
        # Everything in a root level "lib" directory will be excluded from analysis
        # but treated as a dependency
