name: CodeCov
on: [push, pull_request]
jobs:
    coverage:
      name: Combine & check coverage.
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            # Use latest, so it understands all syntax.
            python-version: "3.9"

        - run: python -m pip install --upgrade coverage[toml]

        - name: Download coverage data.
          uses: actions/download-artifact@v2
          with:
            name: coverage-data

        - name: Combine coverage & fail if it's <100%.
          run: |
            python -m coverage combine
            python -m coverage html --skip-covered --skip-empty
            python -m coverage report --fail-under=100          

        - name: Upload HTML report if check failed.
          uses: actions/upload-artifact@v2
          with:
            name: html-report
            path: htmlcov
          if: ${{ failure() }}
