name: CodeCov
on:
  push:
    branches:
      - dev_open_district_upscaling
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’
        
    - name: Generate Report
      run: |
        pip install coverage
        pip freeze
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2

