# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev_open_district_upscaling" branch
  push:
    branches: [ "dev_open_district_upscaling" ]
  pull_request:
    branches: [ "dev_open_district_upscaling" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Duplicate code detection tool
        uses: platisd/duplicate-code-detection-tool@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "program_files/"

