name: Test coverage

on:
  push:
    branches:
      - dev_open_district_upscaling
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’
        
    - name: Generate Report
      run: |
        pip install coverage
        pip freeze
        coverage run -m unittest
